services:
  kilik.translation.command.export:
    class: Kilik\TranslationBundle\Command\ExportCommand
    calls:
        - [ setLoadService, ['@kilik.translation.services.load_translation_service']]
    tags:
        - { name: console.command, command: kilik:translation:export }
  kilik.translation.command.import:
    class: Kilik\TranslationBundle\Command\ImportCommand
    calls:
        - [ setLoadService, ['@kilik.translation.services.load_translation_service']]
    tags:
        - { name: console.command, command: kilik:translation:import }
